# Generated by Django 4.1 on 2024-03-05 14:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teachers", "0003_course_course_category_feedback_course_categories_and_more"),
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="enrolled_courses",
            field=models.ManyToManyField(
                related_name="enrolled_students", to="teachers.course"
            ),
        ),
    ]
