# Generated by Django 4.1 on 2024-03-05 14:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("teachers", "0004_remove_course_students_alter_course_teacher_and_more"),
        ("students", "0002_student_enrolled_courses"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Student",
        ),
    ]
