# Generated by Django 4.1 on 2024-03-05 16:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teachers", "0004_remove_course_students_alter_course_teacher_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="course_pdf",
            field=models.FileField(blank=True, null=True, upload_to="course_pdfs/"),
        ),
    ]
