# Generated by Django 4.1 on 2024-03-05 16:21

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("teachers", "0005_course_course_pdf"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="description",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
