# Generated by Django 4.1 on 2024-03-05 17:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teachers", "0006_course_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="description",
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
