# Generated by Django 4.1 on 2024-03-05 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("teachers", "0007_alter_course_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feedback",
                to="teachers.course",
            ),
        ),
    ]
